{"testCaseId": "57ecab3dd5dff1f42f2587771b09799a", "name": "test_query_message[caseinfo0]", "status": "broken", "labels": [{"name": "parentSuite", "value": "testcases"}, {"name": "suite", "value": "Login_related_test"}, {"name": "subSuite", "value": "TestSendR"}, {"name": "host", "value": "DESKTOP-BQ40Q36"}, {"name": "thread", "value": "197824-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.Login_related_test"}], "fullName": "testcases.Login_related_test.TestSendR#test_query_message", "historyId": "6e947f3342c208d2fcb5db974a8ce910", "stop": 1638502018048, "parameters": [{"name": "caseinfo", "value": "{'method': 'get', 'url': 'http://172.16.11.40:8082/app/newMessage'}"}], "start": 1638502018047, "uuid": "262ca92f-6c7a-4ed5-a53e-8ee9fb1ec400", "statusDetails": {"message": "TypeError: request() takes 2 positional arguments but 3 were given", "trace": "self = <testcases.Login_related_test.TestSendR object at 0x000002D1B145BA20>\ncaseinfo = {'method': 'get', 'url': 'http://172.16.11.40:8082/app/newMessage'}\n\n    @pytest.mark.parametrize(\"caseinfo\",yamlUtil().read_testcase_yaml(\"login_relate.yml\"))\n    def test_query_message(self,caseinfo):\n        method = caseinfo[\"method\"]\n        url = caseinfo[\"url\"]\n        # 从yaml文件读取token值\n        token = yamlUtil().read_relation_yaml()\n        # 调用公共类方法RequestsUtil().send_request（）\n>       rep = RequestsUtil().send_request(method, url, headers=token,data=None)\n\nLogin_related_test.py:35: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <common.requests_util.RequestsUtil object at 0x000002D1B134CF28>\nmethod = 'get', url = 'http://172.16.11.40:8082/app/newMessage', data = None\nkwargs = {'headers': None}\n\n    def send_request(self,method,url,data,**kwargs):\n>       rep = requests.request(method,url,data,**kwargs)\nE       TypeError: request() takes 2 positional arguments but 3 were given\n\n..\\common\\requests_util.py:11: TypeError"}}